version: '2.3'

services:
  set:
    build:
      context: .
      target: prod
      args:
        NODE_PORT: 80
    ports:
      - 8888:80

  setdev:
    build:
      context: .
      target: dev
      args:
        NODE_PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
